#!/bin/bash
########################################################################
# DEBIAN LIVE BUILD SCRIPT
# CREATED   : Eko Saputra (ekovegeance)
# MAIL      : me@ekovegeance.com
# LICENSE   : GNU GPL 3.0
# WEBSITE   : https://www.ekovegeance.com/
# VERSION   : v3.1.1 (06 Sep 2021)
########################################################################

# Menginstall perangkat lunak yang di butuhkan untuk membuat live build 
  sudo apt install live-build 

# Membuat direktori projek
  mkdir distro && cd distro

# Membuat config menggunakan debian live build 
lb config -b iso --security false --updates true -a amd64 --binary-images iso --distribution buster --archive-areas "main contrib non-free" -- debian-installer live --cache-packages true --apt-recommends true --debian-installer-gui false --win32-loader false --iso-application distro --iso-volume distro

# Membuat file iso pertama kali untuk di remastering
  sudo lb build